# PostgreSQL
db_url = "postgresql://postgres:[YOUR-PASSWORD]@db.dgduktxgxyzgqdfzrhwu.supabase.co:5432/postgres"

EMAIL_ADDRESS = "aqualinqs22@gmail.com"
EMAIL_PASSWORD = "aqua22limited."


# Supabase
SUPABASE_URL = "https://dgduktxgxyzgqdfzrhwu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZHVrdHhneHl6Z3FkZnpyaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODk3MzMsImV4cCI6MjA2OTE2NTczM30.JUw6lsJmEPZm_qJI266GzxdCmSdyueA25NHwhCfMC6U"
